<!--
function createWordList()
{
var wl;
var data = new String();
data = "" +
"\"BATTLESHIP\"," +
"\"ANCIENT\"," +
"\"TELEPHONE\"," +
"\"FLEDGLING\"," +
"\"POPSICLE\"," +
"\"CHIPMUNK\"," +
"\"DANGEROUS\"," +
"\"LIGHTNING\"," +
"\"INDUSTRY\"," +
"\"LIGHT BULB\"," +
"\"BURGLAR\"," +
"\"WONDERFUL\"," +
"\"CRITTER\"," +
"\"DINOSAUR\"," +
"\"WATERMELON\"," +
"\"I EAT BOOGERS\"," +
"\"DECIDE\"," +
"\"MOTHER\"," +
"\"CRAYFISH\"," +
"\"SNOWBOARD\"," +
"\"GUITAR\"," +
"\"DRAWING\"," +
"\"PIGLET\"," +
"\"TRANSFORMER\"," +
"\"COMPUTER\"," +
"\"MONKEY\"," +
"\"ROBOT\"," +
"\"RECYCLE\"," +
"\"CHOCOLATE\"," +
"\"FIRE HYDRANT\"," +
"\"MONEY\"," +
"\"PEACE\"," +
"\"PEACH\"," +
"\"DANCE\"," +
"\"QUACK\"," +
"\"CLOWN\"," +
"\"GRAVY\"," +
"\"GAMES\"," +
"\"CAMEL\"," +
"\"PIANO\"," +
"\"SHEEP\"," +
"\"QUEEN\"," +
"\"DREAM\"," +
"\"PEAR\"," +
"\"GUARD\"," +
"\"QUART\"," +
"\"GRAND\"," +
"\"BACKPACK\"," +
"\"AMBULANCE\"," +
"\"STANDARD\"," +
"\"ESCALATOR\"," +
"\"SQUIRREL\"," +
"\"SKATEBOARD\"," +
"\"PICNIC\"," +
"\"SECOND\"," +
"\"PICKLE\"," +
"\"NEEDLE\"," +
"\"PLEASE\"," +
"\"ORANGE\"," +
"\"BUBBLE\"," +
"\"COBBLESTONES\"," +
"\"GRANTED\"," +
"\"EXCITED\"," +
"\"SKEPTIC\"," +
"\"FEATHER\"," +
"\"WEATHER\"," +
"\"TEACHER\"," +
"\"QUARTER\"," +
"\"SPEAKERS\"," +
"\"DOCTOR\"," +
"\"ENDANGER\"," +
"\"HEALTHY\"," +
"\"PLASTIC\"," +
"\"JACK-IN-THE-BOX\"," +
"\"DUCKLING\"," +
"\"FREEZING\"," +
"\"TADPOLE\"," +
"\"FRECKLES\"," +
"\"PENGUIN\"," +
"\"UMBRELLA\"," +
"\"VACUUM\"," +
"\"GRAHAM CRACKERS\"," +
"\"EXCLAMATION POINT\"," +
"\"GOBLIN\"," +
"\"IMAGINATION\"," +
"\"SWEATER\"," +
"\"DIAMOND\"," +
"\"SKATING\"," +
"\"SEASONS\"," +
"\"CRAYONS\"," +
"\"CHOWDER\"," +
"\"INCHWORM\"," +
"\"HICCUPS\"," +
"\"PATCH\"," +
"\"LOCKER\"," +
"\"LADDER\"," +
"\"ICE CREAM\"," +
"\"ELECTRICITY\"," +
"\"PLAYGROUND\"," +
"\"VICTORY\"," +
"\"LEAVES\"," +
"\"CACTUS\"," +
"\"BRAINSTORM\"," +
"\"CRIBBAGE\"," +
"\"TEAPOT\"," +
"\"JACKET\"," +
"\"PEANUT\"," +
"\"BUCKET\"," +
"\"POCKET\"," +
"\"CHEWY\"," +
"\"SHADOW\"," +
"\"FREAKY\"," +
"\"HOCKEY\"," +
"\"TIGER\"," +
"\"TOOTH\"," +
"\"GHOST\"," +
"\"CANYON\"," +
"\"FOGGY\"," +
"\"GROSS\"," +
"\"LION\"," +
"\"MAGIC\"," +
"\"PENNY\"," +
"\"ECHO\"," +
"\"PINKY\"," +
"\"JUICE\"," +
"\"QUICK\"," +
"\"HONEY\"," +
"\"QUIT\"," +
"\"MUMMY\"," +
"\"IGLOO\"," +
"\"PUNCH\"," +
"\"PAINT\"," +
"\"BELLY BUTTON\"," +
"\"FENCE\"," +
"\"QUIET\"," +
"\"JOKER\"," +
"\"NAKED\"," +
"\"QUILT\"," +
"\"LEMON\"," +
"\"NOISE\"," +
"\"FAIRY\"," +
"\"ANKLE\"," +
"\"HELLO\"," +
"\"POLAR BEAR\"," +
"\"CANDY CANE\"," +
"\"RADICAL\"," +
"\"BANANA\"," +
"\"GROWN\"," +
"\"PANDA\"," +
"\"APPLE\"," +
"\"PIZZA\"," +
"\"DESTRUCTION\"," +
"\"KOALA\"," +
"\"EXTRA\"," +
"\"ELBOW\"," +
"\"GIANT\"," +
"\"HEATH\"," +
"\"LEMONADE\"," +
"\"SNOWMAN\"," +
"\"ELEPHANT\"," +
"\"BLIZZARD\"," +
"\"ALLIGATOR\"," +
"\"HOLIDAY\"," +
"\"TUESDAY\"," +
"\"HANDICAPPED\"," +
"\"UNICYCLE\"," +
"\"TRICYCLE\"," +
"\"CONNECT\"," +
"\"GROUND\"," +
"\"ISLAND\"," +
"\"FRIEND\"," +
"\"PRESIDENT\"," +
"\"TORNADO\"," +
"\"REALITY\"," +
"\"POODLE\"," +
"\"CANDLE\"," +
"\"UNIQUE\"," +
"\"JUNGLE\"," +
"\"PEOPLE \"," +
"\"BUMBLEBEE\"," +
"\"EIGHTEEN\"," +
"\"PRETZEL\"," +
"\"FIFTEEN\"," +
"\"SCOOTER\"," +
"\"TWISTER\"," +
"\"MONSTER\"," +
"\"STICKER\"," +
"\"NOODLES\"," +
"\"COOKIES\"," +
"\"CLOTHES\"," +
"\"JELLYFISH\"," +
"\"COLORFUL\"," +
"\"GARBAGE\"," +
"\"FINISH\"," +
"\"LOBSTER\"," +
"\"HULA HOOP\"," +
"\"IMMEDIATE\"," +
"\"MERMAID\"," +
"\"PUMPKIN\"," +
"\"SWIMMING\"," +
"\"GIGGLING\"," +
"\"QUESTION\"," +
"\"GOLDFISH\"," +
"\"TELEVISION\"," +
"\"PANCAKE\"," +
"\"PENCIL\"," +
"\"SCHOOL\"," +
"\"SNOWFLAKES\"," +
"\"DANDILIONS\"," +
"\"ANIMALS\"," +
"\"NIGHTMARE\"," +
"\"CONDOMINIUM\"," +
"\"MERMAN\"," +
"\"VIOLIN\"," +
"\"SAILING\"," +
"\"WALKING\"," +
"\"POISONOUS\"," +
"\"EXCELLENT\"," +
"\"SAILBOAT\"," +
"\"RADIATION\"," +
"\"THERMOMETER\"," +
"\"BALLOON\"," +
"\"HELICOPTER\"," +
"\"HOMEWORK\"," +
"\"COMPUTER\"," +
"\"MULTIPLICATION\"," +
"\"LOLLIPOP\"," +
"\"PINEAPPLE\"," +
"\"SUMMER\"," +
"\"SPIDER\"," +
"\"FINGER\"," +
"\"NUMBER\"," +
"\"DOLLAR\"," +
"\"SUPPER\"," +
"\"TEMPERATURE\"," +
"\"MUSTARD\"," +
"\"KINDERGARTEN\"," +
"\"HAMBURGER\"," +
"\"TYPEWRITER\"," +
"\"UNICORN\"," +
"\"POPCORN\"," +
"\"PEPPERONI\"," +
"\"KANGAROO\"," +
"\"JUMP ROPE\"," +
"\"FLOWERS\"," +
"\"TRAILER\"," +
"\"PRINTS\"," +
"\"TENNIS\"," +
"\"LEOPARD\"," +
"\"PROMISE\"," +
"\"IMPOSSIBLE\"," +
"\"COMPASS\"," +
"\"WOODLAND\"," +
"\"DENTIST\"," +
"\"LIGHT HOUSE\"," +
"\"VIOLET\"," +
"\"SPIRIT\"," +
"\"SILENT\"," +
"\"VELVET\"," +
"\"APPARTMENT\"," +
"\"ELEVATOR\"," +
"\"PILLOW\"," +
"\"UNDERSTAND\"," +
"\"STINKY\"," +
"\"HUNGRY\"," +
"\"GROOVY\"," +
"\"APPROVE\"," +
"\"PRESS\"," +
"\"DONKEY\"," +
"\"BASEBALL\"," +
"\"ACROBAT\"," +
"\"DATABASE\"," +
"\"BLUEBERRIES\"," +
"\"HURRICANE\"," +
"\"APRICOT\"," +
"\"INSECT\"," +
"\"BORED\"," +
"\"THUNDER\"," +
"\"HOT DOG\"," +
"\"MOUSE\"," +
"\"HORSE\"," +
"\"NURSE\"," +
"\"PASTE\"," +
"\"GARDEN\"," +
"\"KITTEN\"," +
"\"MITTENS\"," +
"\"MISTER\"," +
"\"BUTTER\"," +
"\"SISTER\"," +
"\"APRON\"," +
"\"FISHERMAN\"," +
"\"MYSTERY\"," +
"\"MARKET\"," +
"\"CARPET\"," +
"\"PUPPET\"," +
"\"STREET\"," +
"\"TURKEY\"," +
"\"MARINE\"," +
"\"CAREFUL\"," +
"\"GARAGE\"," +
"\"EARTH\"," +
"\"MATCH\"," +
"\"COURAGE\"," +
"\"BIRTHDAY\"," +
"\"KITCHEN\"," +
"\"COLLECTION\"," +
"\"EARTHQUAKE\"," +
"\"CARRIAGE\"," +
"\"OSTRICH\"," +
"\"TIPPING\"," +
"\"VELOCITY\"," +
"\"FASHION\"," +
"\"PATRIOT\"," +
"\"HOSPITAL\"," +
"\"PULSE\"," +
"\"CIRCLE\"," +
"\"LITTLE\"," +
"\"TURTLE\"," +
"\"TATTLE\"," +
"\"PURPLE\"," +
"\"MORALES\"," +
"\"GORILLA\"," +
"\"INTELLIGENT\"," +
"\"ENVELOPE\"," +
"\"FIREMAN\"," +
"\"ESTIMATION\"," +
"\"LAWNMOWER\"," +
"\"EXTINCT\"," +
"\"SPRING\"," +
"\"MAYONNAISE\"," +
"\"PARENTS\"," +
"\"TARANTULA\"," +
"\"SEVENTY\"," +
"\"DISCO\"," +
"\"ASTRONAUT\"," +
"\"VERMIN\"," +
"\"CARROT\"," +
"\"DISCOUNT\"," +
"\"OCTOPUS\"," +
"\"GRUMPY\"," +
"\"MOTORCYCLE\"," +
"\"MARSUPIAL\"," +
"\"SQUARE\"," +
"\"BATHROOM\"," +
"\"SAVIOR\"," +
"\"LANGUAGE\"," +
"\"FRUIT\"," +
"\"CRYSTAL\"," +
"\"PIRATE\"," +
"\"SPRITE\"," +
"\"HAUNTED HOUSE\"," +
"\"FOURTEEN\"," +
"\"LIPSTICK\"," +
"\"COUNTING\"," +
"\"BATHTUB\"," +
"\"PURSUIT\"," +
"\"PORCUPINE\"," +
"\"AARDVARK\"," +
"\"ACTIVITY \"," +
"\"X-RAY\"," +
"\"DIRTY\"," +
"\"PUPPY\"," +
"\"THE END\"";
eval( "wl = new Array( " + data + " );" );
return wl;
}
// -->